(lang dune 3.7)
(using menhir 2.0)
(using mdx 0.2)
(name spectec)

(generate_opam_files true)

(package
  (name spectec)
  (version 0.0.1)
  (maintainers "")
  (depends
    bignum
    core
    core_unix))
