val root : Ssz_schema.t
val transaction : Ssz_schema.t
val transactions : Ssz_schema.t
val roots : int -> Ssz_schema.t
val beacon_block_header : Ssz_schema.t
val deposit_data : Ssz_schema.t
val fork_data : Ssz_schema.t
val withdrawal : Ssz_schema.t
val withdrawals : Ssz_schema.t
val eth1_data : Ssz_schema.t
val execution_payload : Ssz_schema.t
val bls_to_execution_change : Ssz_schema.t
val signed_bls_to_execution_change : Ssz_schema.t
val sync_aggregate : Ssz_schema.t
val voluntary_exit : Ssz_schema.t
val signed_voluntary_exit : Ssz_schema.t
val deposit : Ssz_schema.t
val checkpoint : Ssz_schema.t
val attestation_data : Ssz_schema.t
val attestation : Ssz_schema.t
val indexed_attestation : Ssz_schema.t
val attester_slashing : Ssz_schema.t
val signed_beacon_block_header : Ssz_schema.t
val proposer_slashing : Ssz_schema.t
val fork : Ssz_schema.t
val validator : Ssz_schema.t
val sync_committee : Ssz_schema.t
val execution_payload_header : Ssz_schema.t
val historical_summary : Ssz_schema.t
val beacon_block_body : Ssz_schema.t
val beacon_state : Ssz_schema.t
val deposit_message : Ssz_schema.t
val beacon_block : Ssz_schema.t
